name: Continuous Integration

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run linting
        run: npm run lint

      - name: Dependabot action
        uses: dependabot/dependabot-core@v2.0.0 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: "/"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

