name: Custom Workflow

on:
  push:
    branches: ["main"]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run performance tests
      run: npm run performance-test

    - name: Analyze performance metrics
      run: npm run analyze-performance
