name: Dependency Updates

on:
  schedule:
    - cron: '0 6 * * 0'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Dependabot action
      uses: dependabot/dependabot-core@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: '/'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
